name: Build & Deploy iOS TestFlight

on:
  create:
    tags:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: macos-latest
    env:
      working-directory-ios: ./ios
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.3'
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Import Codesign Certificate
      id: codesign-cert
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}

    - name: Import Provisioning Profile
      id: prov-profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ secrets.APP_BUNDLE_ID }}
        issuer-id: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_CONNECT_API_AUTH_KEY }}
        profile-type: IOS_APP_STORE

    - name: Remove Podfile
      run: rm ios/Podfile

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Increment Build Number (Fastlane)
      env:
        APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        APPSTORE_CONNECT_API_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }}
        APPSTORE_CONNECT_API_AUTH_KEY: ${{ secrets.APPSTORE_CONNECT_API_AUTH_KEY_NEWLINE }}
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
      run: fastlane bump --verbose
      working-directory-ios: ${{ env.working-directory-ios }}

    - name: Build for TestFlight (Fastlane)
      env:
        APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        APPSTORE_CONNECT_API_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }}
        APPSTORE_CONNECT_API_AUTH_KEY: ${{ secrets.APPSTORE_CONNECT_API_AUTH_KEY_NEWLINE }}
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
        APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
        APP_PROVISIONING_PROFILE_NAME: ${{ secrets.APP_PROVISIONING_PROFILE_NAME }}
      run: fastlane build --verbose
      working-directory-ios: ${{ env.working-directory-ios }}

    - name: Upload to TestFlight (Fastlane)
      env:
        APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        APPSTORE_CONNECT_API_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }}
        APPSTORE_CONNECT_API_AUTH_KEY: ${{ secrets.APPSTORE_CONNECT_API_AUTH_KEY_NEWLINE }}
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
      run: fastlane upload --verbose
      working-directory-ios: ${{ env.working-directory-ios }}

